Source/KadOzenka.Web/Models/ExpressScore/CalculateCostTargetObjectViewModel.cs
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using DevExpress.XtraRichEdit.Model;
//using KadOzenka.Dal.Enum;
//using KadOzenka.Dal.ExpressScore.Dto;
//using Newtonsoft.Json;
//using ObjectModel.Directory;
//using ObjectModel.Directory.ES;

//namespace KadOzenka.Web.Models.ExpressScore
//{
//	public class CalculateCostTargetObjectViewModel
//	{
//		/// <summary>
//		/// Площадь для расчета полной стоимости объекта оценки
//		/// </summary>
//		public decimal? Square { get; set; }
//		/// <summary>
//		/// Ид найденных аналогов
//		/// </summary>
//		[Required(ErrorMessage = "Не найдены объекты-аналоги")]
//		public List<int> SelectedPoints { get; set; }

//		/// <summary>
//		/// Ид объекта оценки 
//		/// </summary>
//		[Required(ErrorMessage = "Не найден целевой объект")]
//		public int? TargetObjectId { get; set; }

//        /// <summary>
//        /// Ид целевого объекта из market_core_object
//        /// </summary>
//        public long? TargetMarketObjectId { get; set; }

//        /// <summary>
//        /// Сценарий расчета
//        /// </summary>
//        public ScenarioType ScenarioType { get; set; }

//		/// <summary>
//		/// Сегмент рынка
//		/// </summary>
//		[Required(ErrorMessage = "Выберите сегмент")]
//		public MarketSegment Segment { get; set; }

//		/// <summary>
//		/// Адрес целевого объекта
//		/// </summary>
//		[Required(ErrorMessage = "Не заполнен Адрес")]
//		public string Address { get; set; }

//		/// <summary>
//		/// Кадастровый номер
//		/// </summary>
//		[Required(ErrorMessage = "Не заполнен кадастровый номер")]
//		public string Kn { get; set; }

//		/// <summary>
//		/// Тип сделки
//		/// </summary>
//		[Required(ErrorMessage = "Не заполнен тип сделки")]
//		public DealTypeShort DealType { get; set; }

//		/// <summary>
//		/// Сериализованные данные для расчета 
//		/// </summary>
//		public string ComplexCalculateParameters { get; set; }

//		/// <summary>
//		/// Десерилизованный список параметров для расчета
//		/// </summary>
//		public List<SearchAttribute> DeserializeComplexParameters => JsonConvert.DeserializeObject<List<SearchAttribute>>(ComplexCalculateParameters ?? string.Empty);
//	}
//}

Source/KadOzenka.Web/Models/ExpressScore/SetCommonAttributeEsViewModel.cs
//using System.ComponentModel.DataAnnotations;

//namespace KadOzenka.Web.Models.ExpressScore
//{
//	public class SetCommonAttributeEsViewModel
//	{
//		[Display(Name = "Атрибут кадастрового номера строения")]
//		[Required(ErrorMessage = "Атрибут кадастрового номера строения обязательное")]
//		public long? CadastralNumbeGbuAttributeId { get; set; }

//	}
//}

Source/KadOzenka.Web/Controllers/DataExportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using CommonSdks;
using CommonSdks.PlatformWrappers;
using Core.Register.Enums;
using Core.Shared.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using KadOzenka.Dal.DataExport;
using Core.Main.FileStorages;
using Core.Register;
using ObjectModel.Common;
using Core.SRD;
using KadOzenka.Dal.CommonFunctions;
using KadOzenka.Dal.GbuObject;
using KadOzenka.Web.Attributes;
using KadOzenka.Web.Models.DataImport;

namespace KadOzenka.Web.Controllers
{
	public class DataExportController : KoBaseController
	{
		public DataExportController(IGbuObjectService gbuObjectService, IRegisterCacheWrapper registerCacheWrapper)
			: base(gbuObjectService, registerCacheWrapper)
		{
			
		}

		[HttpGet]
		[SRDFunction(Tag = "")]
		public ActionResult DownloadExportTemplate(long exportId)
		{
			OMExportByTemplates export = OMExportByTemplates
				.Where(x => x.Id == exportId)
				.SelectAll()
				.Execute()
				.FirstOrDefault();

			if (export == null)
			{
				throw new Exception($"В журнале выгрузок не найдена запись с ИД {exportId}");
			}
			var file = DataExporterCommon.GetExportTemplateFileStream(exportId);

			return File(file, GetContentTypeByExtension(export.FileExtension), DataExporterCommon.GetDownloadTemplateFileName(export));
		}

		[SRDFunction(Tag = "")]
		public FileResult DownloadExportResult(long exportId)
		{
			OMExportByTemplates export = OMExportByTemplates
				.Where(x => x.Id == exportId)
				.SelectAll()
				.Execute()
				.FirstOrDefault();

			if (export == null)
			{
				throw new Exception($"В журнале выгрузок не найдена запись с ИД {exportId}");
			}

			var file = DataExporterCommon.GetExportResultFileStream(exportId);

			return File(file, GetContentTypeByExtension(export.FileExtension), DataExporterCommon.GetDownloadResultFileName(export));
		}

		[HttpGet]
		[SRDFunction(Tag = "")]
		public ActionResult RepeatFormation(long exportId)
		{
			OMExportByTemplates export = OMExportByTemplates
				.Where(x => x.Id == exportId)
				.SelectAll()
				.Execute()
				.FirstOrDefault();

			if (export == null)
			{
				throw new Exception($"В журнале выгрузок не найдена запись с ИД {exportId}");
			}

			var resultMessage = DataExporterCommon.RepeatFormation(export);

			return Content(resultMessage);
		}

		[HttpGet]
		[SRDFunction(Tag = "")]
		public IActionResult Details(long objectId)
		{
			OMExportByTemplates export = OMExportByTemplates.Where(x => x.Id == objectId).SelectAll().Execute().FirstOrDefault();

			ViewBag.User = SRDCache.Users[(int)export.UserId].FullName;
			ViewBag.StatusDescription = ((RegistersExportStatus)export.Status).GetEnumDescription();

			var fileSizeFormat = "n2";
			var templateFileInfo = CalculateFileSize(DataExporterCommon.FileStorageName, export.DateCreated,
				DataExporterCommon.GetStorageTemplateFileName(export.Id));
			ViewBag.TemplateFileSizeKb = templateFileInfo.Kb.ToString(fileSizeFormat);
			ViewBag.TemplateFileSizeMb = templateFileInfo.Mb.ToString(fileSizeFormat);

			var resultFileInfo = CalculateFileSize(DataExporterCommon.FileStorageName, export.DateFinished.GetValueOrDefault(),
				DataExporterCommon.GetStorageResultFileName(export.Id));
			ViewBag.ResultFileSizeKb = resultFileInfo.Kb.ToString(fileSizeFormat);
			ViewBag.ResultFileSizeMb = resultFileInfo.Mb.ToString(fileSizeFormat);

			List<ColumnsMappingDto> columnsMappingDtoList = null;
			if (!string.IsNullOrEmpty(export.ColumnsMapping))
			{
				var dbColumns = JsonConvert.DeserializeObject<List<DataExportColumn>>(export.ColumnsMapping);
				columnsMappingDtoList = dbColumns.Select(x => new ColumnsMappingDto
				{
					ColumnName = x.ColumnName,
					AttributeName = RegisterCache.GetAttributeData((int)x.AttributrId).Name,
					IsKey = x.IsKey
				}).ToList();
			}
			ViewBag.ColumnsMappingDtoListJson = JsonConvert.SerializeObject(columnsMappingDtoList);

			return View(export);
		}
	}
}

Source/KadOzenka.Web/Controllers/ExpressScoreController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using CIPJS.Models.ExpressScore;
//using Core.Register;
//using Core.Register.QuerySubsystem;
//using Core.Shared.Extensions;
//using Core.SRD;
//using Core.UI.Registers.CoreUI.Registers;
//using Core.UI.Registers.Helpers;
//using KadOzenka.Dal.Enum;
//using KadOzenka.Dal.ExpressScore;
//using KadOzenka.Dal.ExpressScore.Dto;
//using KadOzenka.Dal.GbuObject;
//using KadOzenka.Dal.Registers;
//using KadOzenka.Dal.ScoreCommon;
//using KadOzenka.Dal.Tours;
//using KadOzenka.Web.Attributes;
//using KadOzenka.Web.Helpers;
//using KadOzenka.Web.Models.ExpressScore;
//using KadOzenka.Web.Models.MarketObject;
//using KadOzenka.Web.SignalR;
//using Kendo.Mvc.UI;
//using MarketPlaceBusiness;
//using MarketPlaceBusiness.Interfaces;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Mvc.Rendering;
//using Microsoft.Extensions.Primitives;
//using Newtonsoft.Json;
//using ObjectModel.Directory;
//using ObjectModel.Directory.ES;
//using ObjectModel.Es;
//using ObjectModel.ES;
//using ObjectModel.Gbu;
//using ObjectModel.KO;
//using ObjectModel.Market;
//using SRDCoreFunctions = ObjectModel.SRD.SRDCoreFunctions;

//namespace KadOzenka.Web.Controllers
//{
//	public class ExpressScoreController : KoBaseController
//	{
//		public static readonly decimal OperatingCostsCoefDefaultValue = 0.81m;

//		#region Init

//		private ExpressScoreService _service;
//		private EsHubService _esHubService;
//		private ScoreCommonService ScoreCommonService { get; set; }
//		private ViewRenderService _viewRenderService;
//		private TourFactorService TourFactorService { get; set; }
//		private IMarketObjectsForExpressScoreService MarketObjectsService { get; }

//		public IRegisterAttributeService RegisterAttributeService { get; set; }

//		public ExpressScoreController(ExpressScoreService service, ViewRenderService viewRenderService,
//			ScoreCommonService scoreCommonService, TourFactorService tourFactorService,
//			IRegisterAttributeService registerAttributeService, EsHubService esHubService,
//			IMarketObjectsForExpressScoreService marketObjectsService)
//		{
//			_service = service;
//			_viewRenderService = viewRenderService;
//			_esHubService = esHubService;
//			ScoreCommonService = scoreCommonService;
//			TourFactorService = tourFactorService;
//			RegisterAttributeService = registerAttributeService;
//			MarketObjectsService = marketObjectsService;
//		}

//		#endregion

//        [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE_CALCULATE)]
//		public ActionResult Index()
//		{
//			return View();
//		}

//        [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE)]
//		public JsonResult GetKadNumber(string address = "")
//		{
//			QSQuery<OMYandexAddress> qSQuery = OMYandexAddress.Where(x => x.FormalizedAddress != null && x.FormalizedAddress.ToLower() == address.ToLower())
//				.Select(x => x.CadastralNumber).Select(x => x.InitialId);

//			var yandexAddress = qSQuery.ExecuteFirstOrDefault();

//			if (yandexAddress == null) return SendErrorMessage("Кадастровый номер для объекта не найден");

//			return Json(new { response = new { kadNumber = yandexAddress.CadastralNumber,  marketObjectId = yandexAddress.InitialId } });
//		}

//        [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE)]
//		public JsonResult GetAddressByKadNumber(string kadNumber)
//		{
//			var yandexAddress = OMYandexAddress.Where(x => x.CadastralNumber == kadNumber)
//                .Select(x => x.FormalizedAddress)
//                .Select(x => x.InitialId)
//                .ExecuteFirstOrDefault();

//			if (yandexAddress == null)
//			{
//				var commonSetting = OMSettingsParams.Where(x => x.SegmentType_Code == MarketSegment.NoSegment)
//					.SelectAll().ExecuteFirstOrDefault();

//				if (commonSetting?.BuildCadNumber == null) 
//				{
//					return SendErrorMessage("Заполните атрибут для поиска кадастрового номера здания");
//				}

//				var obj = OMMainObject.Where(x => x.CadastralNumber == kadNumber).SelectAll().ExecuteFirstOrDefault();

//				if (obj == null)
//				{
//					return SendErrorMessage("В ГБУ не найден объект с указанным кадастровым номером");
//				}

//				var attribute = new GbuObjectService().GetAllAttributes(obj.Id, null, new List<long> {commonSetting.BuildCadNumber.GetValueOrDefault()}, DateTime.Now.Date)?.FirstOrDefault();

//				if (attribute == null || attribute.StringValue.IsNullOrEmpty())
//				{
//					return SendErrorMessage("Адрес для объекта не найден");
//				}

//				yandexAddress = OMYandexAddress.Where(x => x.CadastralNumber == attribute.StringValue)
//                    .Select(x => x.FormalizedAddress)
//                    .Select(x => x.InitialId)
//                    .ExecuteFirstOrDefault();

//				if (yandexAddress == null)
//				{
//					return SendErrorMessage("Адрес для объекта не найден");
//				}

//			}
//			return Json(new { response = new
//            {
//                address = yandexAddress.FormalizedAddress,
//                marketObjectId = yandexAddress.InitialId
//            } });
//		}

//		public ActionResult GetCostFactorsForCalculate(string targetKn, int? targetMarketObjectId, MarketSegment segment)
//		{
//			return PartialView("~/Views/ExpressScore/Partials/PartialComplexCostFactorsForCalculate.cshtml", _service.GetCostFactorsForCalculate(targetKn, targetMarketObjectId, segment));
//		}

//		//TODO Пока заказчик сказал не надо, если и дальше не потребуется то удалить весь связанный код
//   //     [HttpGet]
//   //     [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE_CALCULATE)]
//   //     public ActionResult TargetObjectSubCard(string targetObjectStr)
//   //     {
//   //         var targetObject = JsonConvert.DeserializeObject<TargetObjectDto>(targetObjectStr);

//   //         var model = TargetObjectModel.ToModel(targetObject);
       
//   //         return PartialView("~/Views/ExpressScore/Partials/TargetObjectSubCard.cshtml", model);
//   //     }

//   //     [HttpPost]
//   //     [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE_CALCULATE)]
//   //     public JsonResult TargetObjectSubCard(TargetObjectModel targetObject)
//   //     {
//	  //      if (!ModelState.IsValid)
//		 //       return GenerateMessageNonValidModel();

//	  //      _service.SetTargetObjectAttribute(targetObject.UnitId, targetObject.Attributes.Select(x => x.ToDto()).ToList());
//			//return Json(new {success = true, message = "Значения атрибутов успешно сохранены"});
//   //     }

//        [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE_CALCULATE)]
//		public ActionResult GetNearestObjects([FromQuery] NearestObjectViewModel param)
//		{
//            if (!ModelState.IsValid)  return GenerateMessageNonValidModel();

//            var setting = OMSettingsParams.Where(x => x.SegmentType_Code == param.Segment.GetValueOrDefault()).SelectAll().ExecuteFirstOrDefault();
//            if (setting == null) return SendErrorMessage("Не найдены настройки для выбранного сегмента");

//            var unitsIds = ScoreCommonService.GetUnitsIdsByCadastralNumber(param.Kn, (int)setting.TourId);
//            if (unitsIds.Count == 0) return SendErrorMessage("Выбранный объект не входит в тур или его параметры оценки не заполнены");

//            var costFactor = setting.CostFacrors.DeserializeFromXml<CostFactorsDto>();

//            var targetObject = _service.GetTargetObject(setting, costFactor, unitsIds, param.Kn);
//            if(targetObject == null) return SendErrorMessage("Не найдены данные для выбранного объекта.");

//            var conditionAnalog = 
//				_service.GetSearchConditionForAnalogs(param.DeserializeSearchParameters,param.Segment.GetValueOrDefault(), param.DealType, param.SelectedLng, param.SelectedLat );

//            var analogs = MarketObjectsService.GetNearestObjects(param.ActualDate.Value, conditionAnalog);

//			List<CoordinatesDto> objects = _service.CheckAnalogsByKoFactors(analogs, setting, param.DeserializeSearchParameters);
//			if (objects.Count == 0) return SendErrorMessage("Объекты аналоги не найдены");

//			var coordinatesInput = objects.ToDictionary(x => x.Id.GetValueOrDefault(), y => new CoordinatesDto { Id = y.Id, Lat = y.Lat, Lng = y.Lng });

//			var coordinates = _service.GetCoordinatesPointAtSelectedDistance(coordinatesInput, param.SelectedLat.GetValueOrDefault(), param.SelectedLng.GetValueOrDefault(), param.Quality.GetValueOrDefault());

//			if (coordinates.Count == 0) return SendErrorMessage("Объекты аналоги не найдены");

//			BuildObjectCards(coordinates);

//			return Json(new { response = new { coordinates, targetObjectId = targetObject.UnitId } });
//		}

//		[HttpPost]
//        [SRDFunction(Tag = SRDCoreFunctions.EXPRESSSCORE_CALCULATE)]
//		public ActionResult CalculateCostTargetObject(CalculateCostTargetObjectViewModel viewModel)
//		{
//			if (!ModelState.IsValid)
//			{
//				return GenerateMessageNonValidModel();
//			}

//			var headers = Request.Headers;
//			string connectionId = headers.TryGetValue("connection-signalr-id", out var str) ? (string)str : "";
//			_service.NotifyCalculateProgress += progress => _esHubService.SendCalculateProgress(progress, connectionId);

//			var inputParam = new InputCalculateDto
//			{
//				Address = viewModel.Address,
//				Analogs = MarketObjectsService.GetAnalogsByIds(viewModel.SelectedPoints),
//				DealType = viewModel.DealType,
//				Kn = viewModel.Kn,
//				Square = viewModel.Square.GetValueOrDefault(),
//				ScenarioType = viewModel.ScenarioType,
//				Segment = viewModel.Segment,
//				TargetObjectId = viewModel.TargetObjectId.GetValueOrDefault(),
//                TargetMarketObjectId = viewModel.TargetMarketObjectId,
//                ComplexCalculateParameters = viewModel.DeserializeComplexParameters

Source/KadOzenka.Web/Views/ExpressScore/Partials/PartialGridResultExpressScore.cshtml
@*@using KadOzenka.Dal.Enum
@using KadOzenka.Dal.ExpressScore.Dto
@model ResultCalculateDto

<style type="text/css">
    #gearButton-100_wrapper {
		display: none;
    }

    #showRefreshButton-100 {
		display: none;
    }
	#resultGrid > table {
		table-layout: fixed;
	}
</style>

<div class="form-horizontal col-sm-12">
	<div class="form-group"></div>
	@if (Model.DealType == DealTypeShort.Sale)
	{
		<div class="form-group">
			<div class="col-sm-12">
				<text>Рыночная стоимость объекта оценки, руб: </text><text id="cost">@(Model.SummaryCost.ToString("N"))</text>
			</div>
			<div class="col-sm-12">
				<text>Удельный показатель рыночной стоимости объекта оценки, руб/кв.м: </text><text id="squareCost">@(Model.SquareCost.ToString("N"))</text>
			</div>
			<div class="col-sm-12">
				<text>Адрес объекта оценки: </text><text id="address">@(Model.Address)</text>
			</div>
			<div class="col-sm-12">
				<text>Площадь объекта оценки: </text><text id="area">@(Model.Area)</text>
			</div>
			<div class="col-sm-12">
				<text>Сегмент рынка объекта оценки: </text><text id="marketSegment">@(Model.MarketSegment.GetEnumDescription())</text>
			</div>
			<div class="col-sm-12">
				<text>Тип объекта оценки: </text><text id="marketSegment">@(Model.DealType.GetEnumDescription())</text>
			</div>
		</div>
	}
	
	@if (Model.DealType == DealTypeShort.Rent)
	{
		<div class="form-group">
			<div class="col-sm-12">
				<text>Арендная ставка объекта оценки, руб/год : </text><text id="cost">@((Model.SummaryCost * 12).ToString("N")) </text>
			</div>
			<div class="col-sm-12">
				<text>Арендная ставка объекта оценки, руб/кв. м/год: </text><text id="squareCost">@((Model.SquareCost * 12).ToString("N"))</text>
			</div>
		</div>
	}
	
	<div class="form-group">
		<div class="col-sm-12">
			@if (Model.ReportId != -1)
			{
				<button id="report" data-report-id="@Model.ReportId" class="k-button">Сгенерировать отчет</button>
			}
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<p>Аналоги (@Model.Analogs.Count)</p>
		</div>
		<div id="resultGrid"></div>
	</div>
</div>

<script type="text/x-kendo-template" id="recTemplate">
	<div class="recBtnContainer">
		<button class="k-button" id="recalculateES">Пересчитать</button>
	</div>
</script>

<script type="text/javascript">
	var reportId = "@Model.ReportId";
	var dataGrid = null;
	var data = null;
	var columns = null;
	var expressScoreId = "@ViewBag.EsId";
	try {
		var dataToGridString = JSON.stringify(@Html.Raw(Model.DataToGrid));
		dataGrid = JSON.parse(dataToGridString);

		data = dataGrid.rows.map((arr) => {
			var correctObj = {};
			arr.forEach((obj) => {
				if (parseInt(obj["key"]).valueOf()) {
					correctObj["_" + obj["key"]] = obj["value"];
					return;
				}
				correctObj[obj["key"]] = obj["value"];
			});
			return new Object(correctObj);
		});


		columns = dataGrid.headers.map((item) => { return { title: item.text, field: getCorrectField(item.dataField)} });

		function getCorrectField(dataField) {
			if (parseInt(dataField).valueOf()) return "_" + dataField;
			return dataField;
		}
	} catch (e) {
		console.error("Ошибка при парсинге данных", e);
	}

	var chColumn = [
		{
			title: 'Выбрать все',
			headerTemplate: "<input type='checkbox' id='header-chb' class='k-checkbox header-checkbox'><label class='k-checkbox-label' for='header-chb'></label>",
			template: function (dataItem) {
				return "<input type='checkbox' id='" + dataItem.id + "' class='k-checkbox row-checkbox'><label class='k-checkbox-label' for='" + dataItem.id + "'></label>";
			},
			width: 40
		}
	];



	var checkedIds = {};
	function selectRow() {
		var checked = this.checked,
			row = $(this).closest("tr"),
			grid = $("#resultGrid").data("kendoGrid"),
			dataItem = grid.dataItem(row);

		checkedIds[dataItem.id] = checked;

		if (checked) {
			row.addClass("k-state-selected");

			var checkHeader = true;

			$.each(grid.items(), function (index, item) {
				if (!($(item).hasClass("k-state-selected"))) {
					checkHeader = false;
				}
			});

			$("#header-chb")[0].checked = checkHeader;
		} else {

			row.removeClass("k-state-selected");
			$("#header-chb")[0].checked = false;
		}
	}

	function onDataBound(e) {
		for (var i = 1; i < this.columns.length; i++) {
			this.autoFitColumn(this.columns[i]);
		}
		var view = this.dataSource.view();
		for (var i = 0; i < view.length; i++) {
			if (checkedIds[view[i].id]) {
				this.tbody.find("tr[data-uid='" + view[i].uid + "']")
					.addClass("k-state-selected")
					.find(".k-checkbox")
					.attr("checked", "checked");
			}
		}
	}

	function updateCost(cost, squareCost) {
		if (cost && squareCost) {
			$('#cost').text(cost.toLocaleString());
			$('#squareCost').text(squareCost.toLocaleString());
		}
	}
	function updateReportId(reportId = null) { if (reportId) $('#report').data('report-id', reportId); }
	$(document).ready(function () {
		var grid = $("#resultGrid").kendoGrid({
			height: 510,
			width: "100%",
			resizable: true,
			pageable: {
				pageSize: 5
			},
			dataBound: onDataBound,
			toolbar: kendo.template($("#recTemplate").html()),
			columns: [...chColumn,...columns]
		}).data("kendoGrid");

		grid.table.on("click", ".row-checkbox", selectRow);
		grid.setDataSource(data);

		$('#header-chb').change(function (ev) {
			var checked = ev.target.checked;
			$('.row-checkbox').each(function (idx, item) {
				if (checked) {
					if (!($(item).closest('tr').is('.k-state-selected'))) {
						$(item).click();
					}
				} else {
					if ($(item).closest('tr').is('.k-state-selected')) {
						$(item).click();
					}
				}
			});
		});

		if (reportId === "-1") {
			Common.ShowError("При генерации отчета возникли ошибки. Подробности в журнале ошибок.");
		}
		$('#report').on('click',
			function() {
				var url = "@Url.Action("DownloadExportResult", "DataExport")" + `?exportId=${$(this).data('report-id')}`;
				var a = document.createElement('a');
				a.setAttribute('href', url);
				a.click();
				console.log('report id', $(this).data('report-id'));
			});

		$('#recalculateES').on('click',
			function() {
				var checked = [];
				for (var i in checkedIds) {
					if (checkedIds[i]) {
						checked.push(i);
					}
				}
				var data = {
					analogIds: checked,
					expressScoreId
				}
				progressLoader.loader($('#successDialog'), true);

				var jqxhrReload  =  $.ajax({
					url: "@Url.Action("RecalculateAnalog", "ExpressScore")",
					data,
					method: 'post',
					headers: { 'connection-signalr-id': connectionSignalRId }
				});

				jqxhrReload.done(function (data) {
					if (data.Errors) {
						var errors = getErrors(data.Errors);
						Common.ShowError(errors);
					}
					if (data.success) {
						updateCost(data.success.cost, data.success.squareCost);
						updateReportId(data.success.reportId);
							Common.ShowMessage("Перерасчет успешно выполнен.");
					}

				}).always(function() {
					progressLoader.loader($('#successDialog'), false);
				});
			});
	});
</script>


*@

Source/KadOzenka.Web/Views/ExpressScore/Partials/PartialSimpleFactorCard.cshtml
@*@model KadOzenka.Dal.ExpressScore.Dto.SimpleCostFactor
<div class="form-group">
    <div class="col-sm-2">
        @Html.CustomLabelFor("Имя коэф.", true)
    </div>
    <div class="col-sm-4">
        @Html.Kendo().TextBox().Name($"Name-simple-{ViewBag.Count}").Value(Model.Name)
    </div>
    <div class="col-sm-2">
        @Html.CustomLabelFor("Коэффициент", true)
    </div>
    <div class="col-sm-3">
        @Html.Kendo().NumericTextBox().Name($"Coefficient-simple-{ViewBag.Count}").Spinners(false).Decimals(6).Format("n6").Value(Model.Coefficient.HasValue? (double)Model.Coefficient.GetValueOrDefault() : (double?)null)
    </div>
    <div class="col-sm-1">
        <button disabled="@(!((bool)ViewBag.IsEdit))" type="button" class="k-button-icon k-button remove-simple">
            <span class="k-i-close k-icon"></span>
        </button>
    </div>
</div>

*@