Source/KadOzenka.Web/Models/MarketObject/CoordinatesJoiner.cs
//using ObjectModel.Market;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using MarketPlaceBusiness;
//using MarketPlaceBusiness.Interfaces;

//namespace KadOzenka.Web.Models.MarketObject
//{
//	public class CoordinatesJoiner
//    {
//        private Func<decimal, System.Threading.Tasks.Task> _progress_delegate;
//        private Func<System.Threading.Tasks.Task> _button_state_delegate;
//        private Action<DateTime?, long?, long?, long?> _checking_history_delegate;
//        private IMarketObjectService MarketObjectService { get; }

//        public CoordinatesJoiner(Func<decimal, System.Threading.Tasks.Task> progressDelegate, Func<System.Threading.Tasks.Task> buttonStateDelegate, Action<DateTime?, long?, long?, long?> checkingHistoryDelegate) 
//        {
//            _progress_delegate = progressDelegate;
//            _button_state_delegate = buttonStateDelegate;
//            _checking_history_delegate = checkingHistoryDelegate;
//            MarketObjectService = new MarketObjectService();
//        }

//        public void ManageData(string key)
//        {
//            var AllObjects = MarketObjectService.GetObjectsToAssignCoordinates();
//            int goods = 0, errors = 0, current = 0, allCount = AllObjects.Count;
//            _button_state_delegate.Invoke();
//            AllObjects.ForEach(x =>
//            {
//                try
//                {
//                    OMYandexAddress address = 
//                        new Dal.JSONParser.YandexGeocoder().ParseYandexAddress(
//                            new Dal.WebRequest.YandexGeocoder().GetDataByAddress(
//                                Dal.JSONParser.YandexGeocoder.getFormalizedAddress(x.Address), key)
//                            );
//                    //x.Lng = address.Lng;
//                    //x.Lat = address.Lat;
//                    //x.ProcessType_Code = ObjectModel.Directory.ProcessStep.Dealed;
//                    goods++;
//                }
//                catch (Exception)
//                {
//                    //x.ProcessType_Code = ObjectModel.Directory.ProcessStep.Excluded;
//                    //x.ExclusionStatus_Code = ObjectModel.Directory.ExclusionStatus.NoAddress;
//                    errors++;
//                }
//                //x.Save();
//                _progress_delegate.Invoke((decimal)++current / allCount * 100);
//            });
//            _checking_history_delegate.Invoke(DateTime.Now, allCount, goods, errors);
//        }
//    }
//}

Source/KadOzenka.Web/Models/MarketObject/DistrictsRegionsZonesJoiner.cs
//using ObjectModel.Market;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading;
//using System.Threading.Tasks;
//using MarketPlaceBusiness;
//using MarketPlaceBusiness.Interfaces;

//namespace KadOzenka.Web.Models.MarketObject
//{
//    /// <summary>
//    /// Присвоить округа, районы, зоны
//    /// </summary>
//    public class DistrictsRegionsZonesJoiner
//    {
//        private Func<decimal, System.Threading.Tasks.Task> _progress_delegate;
//        private Func<System.Threading.Tasks.Task> _button_state_delegate;
//        private Action<DateTime?, long?, long?, long?> _checking_history_delegate;
//        private IMarketObjectService MarketObjectService { get; }

//        public DistrictsRegionsZonesJoiner(Func<decimal, System.Threading.Tasks.Task> progressDelegate, Func<System.Threading.Tasks.Task> buttonStateDelegate, Action<DateTime?, long?, long?, long?> checkingHistoryDelegate)
//        {
//            _progress_delegate = progressDelegate;
//            _button_state_delegate = buttonStateDelegate;
//            _checking_history_delegate = checkingHistoryDelegate;
//            MarketObjectService = new MarketObjectService();
//        }

//        public void ManageData()
//        {
//            var AllObjects = MarketObjectService.GetObjectsToAssignDistrictsRegionsAndZones();
//            List<OMQuartalDictionary> QuartalDictionary = OMQuartalDictionary.Where(x => true).SelectAll().Execute().ToList();
//            int allCount = AllObjects.Count, current = 0, correct = 0, error = 0;
//            _button_state_delegate.Invoke();
//            AllObjects.ForEach(x =>
//            {
//                OMQuartalDictionary dictionary = QuartalDictionary.Where(y => x.CadastralQuartal != null && x.CadastralQuartal.Equals(y.CadastralQuartal)).FirstOrDefault();
//                if (dictionary != null)
//                {
//                    //x.District_Code = dictionary.District_Code;
//                    //x.Neighborhood_Code = dictionary.Region_Code;
//                    //x.ZoneRegion = dictionary.ZoneRegion;
//                    //x.Zone = dictionary.Zone;
//                    //x.Save();
//                    correct++;
//                }
//                else error++;
//                _progress_delegate.Invoke((decimal)++current / allCount * 100);
//                //WorkerCommon.SetProgress(processQueue, (int)((double)++current / allCount * 100));
//            });
//            _checking_history_delegate.Invoke(DateTime.Now, allCount, correct, error);
//        }

//    }

//}

Source/KadOzenka.Web/Models/MarketObject/MapObjectDto.cs
using MarketPlaceBusiness.Common.Dto;

namespace KadOzenka.Web.Models.MarketObject
{
	public class MapObjectDto
	{
		public long Id { get; set; }
		public decimal? Latitude { get; set; }
		public decimal? Longitude { get; set; }

		public static MapObjectDto OMMap(MarketObjectDto entity)
		{
			var dto = new MapObjectDto
			{
				Id = entity.Id,
				Latitude = null,
				Longitude = null
			};

			return dto;
		}
	}
}

Source/KadOzenka.Web/Models/MarketObject/MarketSaveObjectDto.cs
using ObjectModel.Directory;

namespace KadOzenka.Web.Models.MarketObject
{
	public class MarketSaveObjectDto
	{
		public long? Id { get; set; }
		public decimal? Lng { get; set; }
		public decimal? Lat { get; set; }
		public PropertyTypesCIPJS? PropertyTypeCode { get; set; }
		public MarketSegment? MarketSegmentCode { get; set; }
		public ProcessStep? StatusCode { get; set; }
		public string EntranceType { get; set; }
		public QualityClass? QualityClassCode { get; set; }
		public string Renovation { get; set; }
		public string BuildingLine { get; set; }
		public long? FloorNumber { get; set; }
	}
}

Source/KadOzenka.Web/Controllers/DataImportController.cs
using System;
using System.Collections.Generic;
using Core.SRD;
using KadOzenka.Dal.DataImport;
using Microsoft.AspNetCore.Mvc;
using ObjectModel.Common;
using System.Linq;
using CommonSdks;
using CommonSdks.PlatformWrappers;
using KadOzenka.Dal.CommonFunctions;
using KadOzenka.Dal.DataExport;
using KadOzenka.Dal.GbuObject;
using KadOzenka.Dal.LongProcess.DataImport;
using KadOzenka.Web.Attributes;
using KadOzenka.Web.Models.DataImport;
using Newtonsoft.Json;
using ObjectModel.Declarations;
using ObjectModel.Directory.Common;

namespace KadOzenka.Web.Controllers
{
	public class DataImportController : KoBaseController
	{
		public DataImportController(IGbuObjectService gbuObjectService, IRegisterCacheWrapper registerCacheWrapper)
			: base(gbuObjectService, registerCacheWrapper)
		{
			
		}

		[HttpGet]
        [SRDFunction(Tag = "")]
		public ActionResult MainData(long importId)
		{
			var import = OMImportDataLog
				.Where(x => x.Id == importId)
				.SelectAll()
				.ExecuteFirstOrDefault();
			var userName = import != null ? SRDCache.Users[(int)import.UserId]?.FullName : string.Empty;
			var status = import != null ? import.Status_Code : (ImportStatus?) null;

			return View(DataImporterLayoutDto.OMMap(import, userName, status));
		}

		[HttpGet]
		[SRDFunction(Tag = "")]
		public ActionResult DownloadImportDataFile(long importId)
		{
			OMImportDataLog import = OMImportDataLog
				.Where(x => x.Id == importId)
				.SelectAll()
				.Execute()
				.FirstOrDefault();

			if (import == null)
			{
				throw new Exception($"В журнале загрузок не найдена запись с ИД {importId}");
			}
			var file = DataImporterCommon.GetImportDataFileStream(importId);

			return File(file, GetContentTypeByExtension(import.FileExtension), DataImporterCommon.GetDownloadDataFileName(import));
		}

		[SRDFunction(Tag = "")]
		public FileResult DownloadImportResultFile(long importId)
		{
			OMImportDataLog import = OMImportDataLog
				.Where(x => x.Id == importId)
				.SelectAll()
				.Execute()
				.FirstOrDefault();

			if (import == null)
			{
				throw new Exception($"В журнале загрузок не найдена запись с ИД {importId}");
			}

			var file = DataImporterCommon.GetImportResultFileStream(importId);

			return File(file, GetContentTypeByExtension(import.FileExtension), DataImporterCommon.GetDownloadResultFileName(import));
		}


	    [HttpGet]
        [SRDFunction(Tag = "")]
		public ActionResult ImportReStart(long importId)
		{
			var import = OMImportDataLog
				.Where(x => x.Id == importId)
				.SelectAll()
				.ExecuteFirstOrDefault();

			if (import == null)
			{
				throw new Exception($"В журнале загрузок не найдена запись с ИД {importId}");
			}

			RepeatFormation(import);

			return Content($"Выполнено повторное формирование файла по шаблону {import.DataFileTitle}");
		}


		#region Support Methods

		public static void RepeatFormation(OMImportDataLog import)
		{
			if (string.IsNullOrEmpty(import.DataFileName))
			{
				throw new Exception("Не задан шаблон файла");
			}

			var fileStream = DataImporterCommon.GetImportDataFileStream(import.Id);
			List<DataExportColumn> columns = JsonConvert.DeserializeObject<List<DataExportColumn>>(import.ColumnsMapping);
			if (import.MainRegisterId == OMDeclaration.GetRegisterId())
			{
				DataImporterDeclarations.AddImportToQueue(OMDeclaration.GetRegisterId(), "DeclarationsDeclaration", import.DataFileTitle, fileStream,
					columns);
			}
			else
			{
				DataImporterByTemplateLongProcess.AddImportToQueue(import.MainRegisterId, import.RegisterViewId, import.DataFileTitle, fileStream, columns, import.DocumentId);
			}
		}

		#endregion
	}
}

Source/KadOzenka.Web/Controllers/MarketObjectsController.cs
using System;
using System.IO;
using System.Linq;
using System.IO.Compression;
using System.Collections.Generic;
using CommonSdks;
using CommonSdks.PlatformWrappers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ObjectModel.Market;
using KadOzenka.Web.Models.MarketObject;
using Core.Main.FileStorages;
using Core.Register.QuerySubsystem;
using Core.Shared.Extensions;
using Core.UI.Registers.CoreUI.Registers;
using KadOzenka.Dal.CommonFunctions;
using KadOzenka.Dal.GbuObject;
using KadOzenka.Web.Attributes;
using MarketPlaceBusiness.Common.Interfaces;
using SRDCoreFunctions = ObjectModel.SRD.SRDCoreFunctions;

namespace KadOzenka.Web.Controllers
{
    public class MarketObjectsController : KoBaseController
	{
		public IMarketObjectService MarketObjectsService { get; set; }

        public MarketObjectsController(IMarketObjectService marketObjectsService, IRegisterCacheWrapper registerCacheWrapper,
	        IGbuObjectService gbuObjectService)
	        : base(gbuObjectService, registerCacheWrapper)
        {
	        MarketObjectsService = marketObjectsService;
        }

        [HttpGet]
        [SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        public IActionResult ObjectCard(long id)
        {
	        List<OMPriceHistory> priceHistory = null;
            var analogItem = MarketObjectsService.GetMappedObjectById(id);
            if (analogItem != null)
            {
	            priceHistory = ObjectModel.Market.OMPriceHistory.Where(x => x.InitialId == id).SelectAll().Execute();
            }
            return View(CoreObjectDto.OMMap(analogItem, priceHistory));
		}

        [HttpGet]
        [SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        public ActionResult GetChartData(long? id)
		{
			if (!id.HasValue) throw new Exception("Не передан идентификатор объекта.");
			var priceHistories = ObjectModel.Market.OMPriceHistory.Where(x => x.InitialId == id.Value).SelectAll().Execute();
			return Content(JsonConvert.SerializeObject(PriceHistoryChartModel.FromEntities(priceHistories)), "application/json");
		}

        //[HttpGet]
        //[SRDFunction(Tag = SRDCoreFunctions.MARKET_ACTIVATE_PROCESS)]
        //public ActionResult ActivateProcess()
        //{
        //    return View("~/Views/AnalogCheck/ActivateDistrictsRegionsZones.cshtml");
        //}

        [HttpGet]
        [SRDFunction(Tag = SRDCoreFunctions.MARKET_ACTIVATE_COORDINATES)]
        public ActionResult ActivateCoordinates()
        {
            return View("~/Views/AnalogCheck/ActivateCoordinates.cshtml");
        }


        #region Outliers Checking

        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public ActionResult GetMarketSegmentList()
        //{
	       // var exceptions = new List<long> { (long)MarketSegment.None, (long)MarketSegment.NoSegment };
	       // var segments = Helpers.EnumExtensions.GetSelectList(typeof(MarketSegment), exceptions: exceptions);

	       // return Content(JsonConvert.SerializeObject(segments), "application/json");
        //}

        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public ActionResult GetMarketPropertyTypeDivisionsList()
        //{
	       // var propertyTypes = Helpers.EnumExtensions.GetSelectList(typeof(ObjectPropertyTypeDivision));
	       // return Content(JsonConvert.SerializeObject(propertyTypes), "application/json");
        //}

        //[HttpGet]
        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public ActionResult OutliersSettings(bool isPartialView = false)
        //{
	       // ViewBag.isPartialView = isPartialView;
        //    return View("~/Views/MarketObjects/OutliersCheckingSettings.cshtml");
        //}

        //[HttpGet]
        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public JsonResult GetOutliersSettingsCoefficients()
        //{
	       // var settingsDto = OutliersCheckingSettingsService.GetOutliersCheckingSettings();
	       // var models = OutliersSettingsModel.FromDto(settingsDto);

        //    return Json(models);
        //}

        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public JsonResult UpdateOutliersSettingsCoefficients(string modelJson)
        //{
	       // var model = JsonConvert.DeserializeObject<OutliersSettingsModel> (modelJson);
	       // OutliersCheckingSettingsService.UpdateOutliersCheckingSettings(model.ToDto());

	       // return Json(new[] { model });
        //}

        //[HttpGet]
        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public IActionResult OutliersCheckingSettingsImport()
        //{
	       // return View(new OutliersSettingsImportModel());
        //}

        //[HttpPost]
        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public IActionResult OutliersCheckingSettingsImport(IFormFile file, OutliersSettingsImportModel viewModel)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return GenerateMessageNonValidModel();
        //    }

        //    object returnedData;
        //    try
        //    {
	       //     using (var stream = file.OpenReadStream())
	       //     {
		      //      var settingDto = viewModel.ToDto(file);
		      //      var importId = OutliersCheckingSettingsService.ImportOutliersCheckingSettingsFromExcel(stream, settingDto);
		      //      returnedData = new
		      //      {
			     //       importId
		      //      };
	       //     }
        //    }
        //    catch (Exception ex)
        //    {
	       //     ErrorManager.LogError(ex);
	       //     return BadRequest();
        //    }

        //    return Content(JsonConvert.SerializeObject(returnedData), "application/json");
        //}

        //[SRDFunction(Tag = SRDCoreFunctions.MARKET)]
        //public ActionResult PerformOutliersChecking(OutliersCheckingPerformModel model)
        //{
	       // if (!ModelState.IsValid)
	       // {
		      //  return GenerateMessageNonValidModel();
	       // }
        //    ////For testing
        //    //var settings = model.ToSettings();
        //    //var history = new OMOutliersCheckingHistory
        //    //{
        //    //    DateCreated = DateTime.Now,
        //    //    Status_Code = ObjectModel.Directory.Common.ImportStatus.Added,
        //    //    PropertyTypesMapping = !settings.AllPropertyTypes
	       //    //     ? JsonConvert.SerializeObject(settings.PropertyTypes)
	       //    //     : null,
        //    //};
        //    //if (settings.Segment.HasValue)
        //    //    history.MarketSegment_Code = settings.Segment.Value;
        //    //history.Save();
        //    //new OutliersCheckingLongProcess().StartProcess(new OMProcessType(), new OMQueue
        //    //{
        //    //    Status_Code = Status.Added,
        //    //    UserId = SRDSession.GetCurrentUserId(),
        //    //    Parameters = settings.SerializeToXml(),
        //    //    ObjectId = history.Id
        //    //}, new CancellationToken());

        //    OutliersCheckingLongProcess.AddProcessToQueue(model.ToSettings());

        //    return Ok();
        //}

        #endregion Outliers Checking
    }
}

Source/KadOzenka.Web/Views/MarketObjects/CorrectionByRoomDetailedHistory.cshtml
<div class="form-horizontal col-sm-12">
    <div class="general-info">
        <div class="form-group">
            <div class="col-sm-2">
                <label>@ViewBag.MarketSegment</label>
            </div>
            <div class="col-sm-2">
                <label>@ViewBag.Date.ToString("MMMM yyyy")</label>
            </div>
        </div>
    </div>
    <div id="grid"></div>
</div>


<script id="GridToolbarTemplate" type="text/x-kendo-template">
    <div style="float: left">
        <a class="k-button k-button-icon" id="excludeBtn" style="width:120px;">
            <span class="k-icon k-i-save" style="padding-right: 30%"></span>
            Исключить
        </a>
    </div>

</script>


@section styles {
    <style>
        .general-info {
            font-size: 120%;
            padding: 1% 0 0 1%; 
        }

        .k-header {
            text-align: center !important;
        }

        #grid {
            text-align: center;
        }
    </style>
}


<script type="text/javascript">
    $(document).ready(function () {
        var dataSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: '@Html.Raw(Url.Action("GetCorrectionByRoomDetailedHistory", "MarketObjects", new { marketSegmentCode = ViewBag.MarketSegmentCode, date = ViewBag.Date }))',
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json'
                }
            },
            schema: {
                model: {
                    id: "Id",
                    fields: {
                        Id: {editable: false, nullable: true},
                        BuildingCadastralNumber: { editable: false },
                        OneRoomCoefficient: { editable: false },
                        ThreeRoomsCoefficient: { editable: false },
                        IsExcludeFromCalculation: { type: "boolean" }
                    }
                }
            },
            pageSize: 15
        });

        $("#grid").kendoGrid({
            dataSource: dataSource,
            toolbar: kendo.template($("#GridToolbarTemplate").html()),
            pageable: true,
            columns: [
                {
                    title: "Кадастровый номер здания",
                    field: "BuildingCadastralNumber"
                },
                {
                    title: "Коэффициент на 1-но комнатную квартиру",
                    field: "OneRoomCoefficient"
                },
                {
                    title: "Коэффициент на 3-х комнатную квартиру",
                    field: "ThreeRoomsCoefficient"
                },
                {
                    title: "Исключен из расчета",
                    field: "IsExcludeFromCalculation",
                    template: '<input type="checkbox" #= IsExcludeFromCalculation ? \'checked="checked"\' : "" # class="chkbx" />'
                }
            ]
        });

        $("#grid .k-grid-content").on("change", "input.chkbx", UpdateGridDataSource);
        $('#excludeBtn').on('click', ExcludeBuildingsFromCalculation);
    });




    function UpdateGridDataSource(e) {
        var grid = $("#grid").data("kendoGrid");
        var dataItem = grid.dataItem($(e.target).closest("tr"));
        dataItem.IsExcludeFromCalculation = this.checked;
        dataItem.IsDirty = true;
    }

    function ExcludeBuildingsFromCalculation() {
        var models = $("#grid").data("kendoGrid").dataSource.data();
        kendo.ui.progress($('body'), true);
        $.ajax({
            type: 'POST',
            url: '@Url.Action("ChangeBuildingsStatusInCalculation", "MarketObjects")',
            data: { models: JSON.stringify({ models }) },
            success: function (response) {
                Common.ShowMessage(response.Message);
            },
            error: function(response) {
                Common.ShowError(response.responseText);
            },
            complete: function() {
                kendo.ui.progress($('body'), false);
            }
        });
    }

</script>

Source/KadOzenka.Web/Views/MarketObjects/OutliersCheckingSettingsImport.cshtml
@*@model KadOzenka.Web.Models.MarketObject.OutliersSettingsImportModel

@using (Html.BeginForm("OutliersCheckingSettingsImport", "MarketObjects", FormMethod.Post))
{
    <div class="form-horizontal col-sm-12">
        <div class="form-group"></div>
        <div class="form-group">
            <input name="files" id="files" type="file" aria-label="files" accept=".xls,.xlsx" />
        </div>
        <fieldset class="outliers-settings-import-fieldset">
            <legend>Соотношение параметров и столбцов файла</legend>
            <div class="form-group">
                <div class="col-sm-2">
                    @Html.CustomLabelFor(m => m.ZoneColumnName)
                </div>
                <div class="col-sm-10">
                    @Html.Kendo().DropDownListFor(m => m.ZoneColumnName).DataTextField("Name").DataValueField("Name")
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">
                    @Html.CustomLabelFor(m => m.DistrictColumnName)
                </div>
                <div class="col-sm-10">
                    @Html.Kendo().DropDownListFor(m => m.DistrictColumnName).DataTextField("Name").DataValueField("Name")
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">
                    @Html.CustomLabelFor(m => m.RegionColumnName)
                </div>
                <div class="col-sm-10">
                    @Html.Kendo().DropDownListFor(m => m.RegionColumnName).DataTextField("Name").DataValueField("Name")
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">
                    @Html.CustomLabelFor(m => m.MinCoefColumnName)
                </div>
                <div class="col-sm-10">
                    @Html.Kendo().DropDownListFor(m => m.MinCoefColumnName).DataTextField("Name").DataValueField("Name")
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">
                    @Html.CustomLabelFor(m => m.MaxCoefColumnName)
                </div>
                <div class="col-sm-10">
                    @Html.Kendo().DropDownListFor(m => m.MaxCoefColumnName).DataTextField("Name").DataValueField("Name")
                </div>
            </div>
        </fieldset>
        <div class="form-group">
            <div class="col-sm-offset-9 col-sm-3">
                @Html.Kendo().CheckBoxFor(x => x.DeleteOldValues)
            </div>
        </div>
        <div class="form-group">
            <div>
                <span>
                    <button id="outliersCheckingImportButton" type="button" class="k-button" style="float: right">Загрузить</button>
                </span>
            </div>
        </div>
    </div>
}

@section styles {
    <style>
        .form-horizontal .form-group {
            margin-right: 0;
            margin-left: 0;
        }

        fieldset.outliers-settings-import-fieldset {
            border: 1px solid #c8c6cc;
            border-radius: 10px;
            margin-bottom: 0.8em;
        }

        fieldset.outliers-settings-import-fieldset legend {
            font-size: initial;
            margin: 10px;
        }

    </style>
}

<script src="~/js/custom-validation.js"></script>
<script>
    var dataSource = new kendo.data.DataSource({
        data: [ ]
    });
    var uploadControl;

    $(document).ready(function () {
        $(`#@(nameof(Model.ZoneColumnName))`).data('kendoDropDownList').setDataSource(dataSource);
        $(`#@(nameof(Model.DistrictColumnName))`).data('kendoDropDownList').setDataSource(dataSource);
        $(`#@(nameof(Model.RegionColumnName))`).data('kendoDropDownList').setDataSource(dataSource);
        $(`#@(nameof(Model.MinCoefColumnName))`).data('kendoDropDownList').setDataSource(dataSource);
        $(`#@(nameof(Model.MaxCoefColumnName))`).data('kendoDropDownList').setDataSource(dataSource);

        uploadControl = $('#files').kendoUpload({
            multiple: false,
            localization: {
                select: 'Загрузить Файл'
            },
            async: {
                autoUpload: true,
                saveUrl: '@Url.Action("ParseFileColumns", "DataImportByTemplate")'
            },
            validation: {
                allowedExtensions: ['.xls', '.xlsx']
            },
            success: function (e) {
                if (e.operation === "upload") {
                    dataSource.data(e.response.ColumnsNames);
                }
            },
            error: function (e) {
                dataSource.data([]);
                if (e.XMLHttpRequest.responseText) {
                    Common.ShowError(e.XMLHttpRequest.responseText);
                } else {
                    Common.ShowError("Не удалось загрузить выбранный файл");
                }
            },
            clear: function (e) {
                dataSource.data([]);
            }
        }).data('kendoUpload');

        $('#outliersCheckingImportButton').on('click',
            function () {
	            var form = $('form');
                var formObject = Common.Functions.FormToObject(form);

                var files = uploadControl.getFiles();
                if (files.length === 0) {
                    Common.ShowError("Файл не выбран");
                    return;
                }

                var formData = new FormData();
                formData.append("viewModel.ZoneColumnName", formObject.ZoneColumnName);
                formData.append("viewModel.DistrictColumnName", formObject.DistrictColumnName);
                formData.append("viewModel.RegionColumnName", formObject.RegionColumnName);
                formData.append("viewModel.MinCoefColumnName", formObject.MinCoefColumnName);
                formData.append("viewModel.MaxCoefColumnName", formObject.MaxCoefColumnName);
                formData.append("viewModel.DeleteOldValues", formObject.DeleteOldValues);
                formData.append("file", files[0].rawFile);
	            kendo.ui.progress($('body'), true);
                $.ajax({
                    type: 'POST',
                    url: form.attr('action'),
                    data: formData,
                    contentType: false,
                    processData: false,
                    dataType: 'json',
					success: function (response) {
                        if (response.Errors) {
                            var errors = getErrors(response.Errors);
                            Common.ShowError(errors);
                            return;
                        }

                        window.location = '@Url.Action("DownloadImportResultFile", "DataImport")' + '?importId=' + response.importId;
                        Common.ShowMessage('Данные успешно импортированы');
                    },
                    error: function (response) {
                        Common.ShowError(response.responseText);
                    },
                    complete: function (data) {
                        kendo.ui.progress($('body'), false);
                    }
                });
            });
    });
</script>

*@