Source/KadOzenka.Web/Models/UnloadResults/UnloadResultsDownloadModel.cs
namespace KadOzenka.Web.Models.UnloadResults
{
    public class UnloadResultsDownloadModel
    {
        public long Id { get; set; }
        public bool FileExists { get; set; }
        public string FileName { get; set; }
    }
}

Source/KadOzenka.Web/Controllers/UnloadResultsController.cs
using System;
using CommonSdks;
using CommonSdks.PlatformWrappers;
using Core.Shared.Extensions;
using Core.SRD;
using KadOzenka.Dal.CommonFunctions;
using KadOzenka.Dal.DataExport;
using KadOzenka.Dal.GbuObject;
using Microsoft.AspNetCore.Mvc;
using KadOzenka.Web.Attributes;
using KadOzenka.Web.Models.GeneralReports;
using KadOzenka.Web.Models.UnloadResults;

namespace KadOzenka.Web.Controllers
{
	public class UnloadResultsController : KoBaseController
	{
		public UnloadResultsController(IRegisterCacheWrapper registerCacheWrapper, IGbuObjectService gbuObjectService)
			: base(gbuObjectService, registerCacheWrapper)
		{
		}


		[SRDFunction(Tag = "")]
		public FileResult DownloadResult(long resultFileId)
		{
			var fileName = UnloadResultStorageManager.GetUnloadResultFileNameOrDefault(resultFileId);
			var content = UnloadResultStorageManager.GetUnloadResultFileById(resultFileId);
			var contentType = UnloadResultStorageManager.GetUnloadResultContentType(resultFileId);
			return File(content, contentType, fileName);
		}

		[HttpGet]
		[SRDFunction(Tag = "")]
		public IActionResult UnloadResultsModal(long? resultFileId)
		{
			var model = new UnloadResultsDownloadModel();
			if (!resultFileId.HasValue)
			{
				model.FileExists = false;
			}
			else
			{
				var id = resultFileId.Value;
				var exists = UnloadResultStorageManager.CheckIfFileExists(id);
				var fileName = UnloadResultStorageManager.GetUnloadResultFileNameOrDefault(id);
				model = new UnloadResultsDownloadModel {FileExists = exists, FileName = fileName, Id = id};
			}

			return View(model);
		}
	}
}

Source/KadOzenka.Web/Views/UnloadResults/UnloadResultsModal.cshtml
@model KadOzenka.Web.Models.UnloadResults.UnloadResultsDownloadModel

<div class="center">
    @if (Model.FileExists)
        {
            @Html.ActionLink($"Скачать {Model.FileName}", "DownloadResult", "UnloadResults", new { resultFileId = Model.Id}, new {@class = "k-button"});
        }
        else {
            <p>Файл не найден на сервере</p>
        }
</div>

<style>
    .mainContent{
        display: flex;
        justify-content: center;
        flex-direction: column;
    }
</style>